[package]
name = "quircs"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libc = "0.2"

[dev-dependencies]
image = "0.23.4"


