[package]
name = "quircs"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
version = "1.0.0"
edition = "2018"
license = "MIT"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
num-derive = "0.3.0"
num-traits = "0.2.11"
thiserror = "1.0.19"

[dev-dependencies]
image = "0.23.4"


